license = "All rights reserved" 
loaderVersion = "[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
modLoader = "javafml" #mandatory
[[mods]] #mandatory
authors = "BalkondeurAlpha" #optional
credits = "" #optional
description = '''
''' 
displayName = "Archimedes' Ships" #mandatory
logoFile = "archimedesships_logo.png" #optional
modId = "archimedesships" #mandatory
version = "${file.jarVersion}" #mandatory
[[dependencies.archimedesships]] #optional
mandatory = true #mandatory
modId = "forge" #mandatory
ordering = "NONE" 
side = "BOTH" 
versionRange = "[37,)" #mandatory
[[dependencies.archimedesships]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.17.1,1.18)"
